### ISSUE TITLE
Blank page when element is added

### ISSUE THREAD

**Issue by antonh1611** [nkolban/google-maps-coachview#1]
Hello,
i am facing a problem with the google map coach.
When i add it to my page, the page displays blank and i get the exception in the console log:
***local:9443/teamworks/script/coachNG/dojo/1.10.3/jquery.js 404 (Not Found).
I tried to find the reference to the missing jquery.js file, but i have not found it, so i added the jquery file manually, and added the reference to the jquery in the coach, but this does not help.
Can you please advise me how to fix this?
Regards
Anton

**Comment by nkolban** [comment]
Howdy Anton,
Can you clarify how you installed the Coach View?  Did you download the TWX and install the TWX file?

**Comment by antonh1611** [comment]
Hi,
yes, i imported the twx in the process center toolkit.
I am sorry for bothering,
i just figured out that it must be included in the client-side human service, not the heritage human service.
Thank you and sorry for bothering.

**Comment by nkolban** [comment]
Anton,
Many thanks for taking the time to respond.  You didn't bother me at all ... I hope you found something useful in the project.

Neil
